### ISSUE TITLE
number of opened and closed ticket by month

### ISSUE THREAD

**Issue by yalgva** [InfotelGLPI/mydashboard#71]
Hello,

Would it be possible to add technician group in option of this chart please ?

Thank you so much for your work

**Comment by yalgva** [comment]
Hello,

not lucky because you add technician not technician group.

Thx

**Comment by mate-infotel** [comment]
Hi.

**Comment by yalgva** [comment]
I confirm I need technician group

**Comment by yalgva** [comment]
1.7.4 version, I think about a bug to backlog orange line because we have 122 tickets not 0 today
![image](https://user-images.githubusercontent.com/30655170/57622954-ff449000-758e-11e9-94a6-fc1591ea6d43.png)

**Comment by mate-infotel** [comment]
It's not a bug because datas used to display the orange line are not live datas.

These datas are an image of tickets state at the moment they have been taken.

You need to execute the php file located in glpi/plugins/mydashboard/scripts/insert_stock_tickets.php.

This file must be executed at the end of every month to update datas.

It's normal that values in the orange line don't change when you use filters on the widget. Datas are based by Entity and not by groups.

**Comment by yalgva** [comment]
in 1.6.6 I had the same value of backlog in orange line
![image](https://user-images.githubusercontent.com/30655170/57624860-17b6a980-7593-11e9-8f3f-a4c916cc9a2a.png)

**Comment by mate-infotel** [comment]
I can say that "stock de tickets" and "Nombre de tickets ouverts et clos par mois" have the same values here.

**Comment by yalgva** [comment]
So why it is not the same on my dashboard ? 

ps : on peut parler français si cela vous arrange

**Comment by mate-infotel** [comment]
(Cela m'arrange mais les anglophones qui lisent moins ;) ).

Les valeurs sont les mêmes c'est jusque que la ligne orange est placée sur les valeurs en bleu et non l'inverse.

The values are the same but the orange line is different because values of stock ticket are displayed on the tickets values and not otherwise.

**Comment by yalgva** [comment]
ce qui est bizarre c'est que sur les versions précédentes la valeur etait juste et devant
![image](https://user-images.githubusercontent.com/30655170/57672343-05328380-7618-11e9-8334-c9024660bdee.png)

**Comment by Hanns-G** [comment]
> 
> 
> I confirm I need technician group

I do agree. It would be great to have a filter "Technician Group", and in particular on the widget "Number of opened and closed ticket by month", "The average real duration of treatment of the ticket" and SLA graphs.

I'm taking this opportinuty to thank you for your amazing job (infotel, teclib  & contributors). GLPI is huge !

**Comment by tsmr** [comment]
Old ticket i close
