### ISSUE TITLE
How to create new columns?

### ISSUE THREAD

**Issue by henriquearthur** [InfotelGLPI/mydashboard#97]
How can I add new columns to widgets that list certain tickets?

I know it's probably not possible through the interface, so if you can point where in the code I should look at to add columns like creation date and SLA progress I would appreciate.

Thanks

**Comment by keha35** [comment]
Hi,

It's indeed not possible through the interface.
I can't point where in the code you need to check because it depend which graph you want to update.
You need to update the sql query to get the data and then update the header in the output.
All the reports are in the folder "reports" of the plugin.
